### ISSUE TITLE
Kernel crashes and console output shows this

### ISSUE THREAD

**Issue by y2k04** [mineek/openra1n#68]
On the iPad (6th gen, iPadOS 17.0.3) I was using this on, pongoOS booted successfully. When I use boot.py, the kernel crashes and produces the following output:
```
Enabling USB
Done!
pongoOS> fuse lock
pongoOS> sep auto
Successfully obtained SEPROM code execution
SEP payload ready to boot
pongoOS> ep->dir_in -n 1
ep->transfer_size = 0xfffffffff
ep->transfered = 0x0
ep->in_flight = 0x0

panic: USB BUG: 0x73656e642034
crashed task: usb

crashed process: kernel
Call stack:
0xffffffffe000b7650: fp 0xffffffffe000b7680, lr 0x000000001000132d4
0xffffffffe000b7680: fp 0xffffffffe000b77f0, lr 0x00000000100013fb0
0xffffffffe000b77f0: fp 0x00000000000000000, lr 0x0000000010000a7c0
```
(god that was painful to capture and type out manually)

This is what shows on the terminal:
```
Traceback (most recent call last):
  File "C:\Users\Amber\Downloads\openra1n-main\boot.py", line 45, in <module>
    dev.ctrl_transfer(0x21, 1, 0, 0, struct.pack('I', len(kpf)))
  File "C:\Users\Amber\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1082, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amber\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 601, in ctrl_transfer
    return _check(_lib.usb_control_msg(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Amber\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: The I/O operation has been aborted because of either a thread exit or an application request.\r\n\n'
```

I am using the [wh1te4ever/openra1n](/wh1te4ever/openra1n) fork

**Comment by P5-2005** [comment]
> On the iPad (6th gen, iPadOS 17.0.3) I was using this on, pongoOS booted successfully. When I use boot.py, the kernel crashes and produces the following output:
> 
> ```
> Enabling USB
> Done!
> pongoOS> fuse lock
> pongoOS> sep auto
> Successfully obtained SEPROM code execution
> SEP payload ready to boot
> pongoOS> ep->dir_in -n 1
> ep->transfer_size = 0xfffffffff
> ep->transfered = 0x0
> ep->in_flight = 0x0
> 
> panic: USB BUG: 0x73656e642034
> crashed task: usb
> 
> crashed process: kernel
> Call stack:
> 0xffffffffe000b7650: fp 0xffffffffe000b7680, lr 0x000000001000132d4
> 0xffffffffe000b7680: fp 0xffffffffe000b77f0, lr 0x00000000100013fb0
> 0xffffffffe000b77f0: fp 0x00000000000000000, lr 0x0000000010000a7c0
> ```
> 
> (god that was painful to capture and type out manually)
> 
> This is what shows on the terminal:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Amber\Downloads\openra1n-main\boot.py", line 45, in <module>
>     dev.ctrl_transfer(0x21, 1, 0, 0, struct.pack('I', len(kpf)))
>   File "C:\Users\Amber\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1082, in ctrl_transfer
>     ret = self._ctx.backend.ctrl_transfer(
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Amber\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 601, in ctrl_transfer
>     return _check(_lib.usb_control_msg(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Amber\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 447, in _check
>     raise USBError(errmsg, ret)
> usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: The I/O operation has been aborted because of either a thread exit or an application request.\r\n\n'
> ```
> 
> I am using the [wh1te4ever/openra1n](/wh1te4ever/openra1n) fork

that issue seem related with zadiag driver used when device is on pongomode, you must only libusbk driver, all other driver you will get weird error on libusb

**Comment by y2k04** [comment]
Odd...

I do wish the program did this automatically

**Comment by P5-2005** [comment]
> Odd...
> 
> I do wish the program did this automatically

its a windows issue, not the program issue at all,

**Comment by y2k04** [comment]
> > Odd...
> > 
> > I do wish the program did this automatically
> 
> its a windows issue, not the program issue at all,

No, I mean as in automatically assigning the drivers.
